### ISSUE TITLE
Problem during run and during unitest.sh

### ISSUE THREAD

**Issue by desmodus1984** [pkubioinformatics/nanoreviser#2]
Hi,
I installed the gpu version of nanoreviser, and everything supposedly when ok, but the unitest.sh failed:
(nanorev) [jpac1984@o0311 nanoreviser]$ sh unitest.sh 
Traceback (most recent call last):
  File "NanoReviser.py", line 26, in <module>
    from albacore.path_utils import get_default_path
ModuleNotFoundError: No module named 'albacore'
Traceback (most recent call last):
  File "NanoReviser_train.py", line 25, in <module>
    from albacore.path_utils import get_default_path
ModuleNotFoundError: No module named 'albacore'
Traceback (most recent call last):
  File "./unitest/check_nanoreviser.py", line 26, in <module>
    with open(log_fn, 'r') as lg:
FileNotFoundError: [Errno 2] No such file or directory: './unitest/unitest_log.txt'
unitest has been completed.

Also, then I thought, that I might have been the case of the test, so I tried running a test with some real data, and it failed too.
Here is the command line:
(nanorev) [jpac1984@o0311 nanoreviser]$ python NanoReviser.py -d /fs/scratch/PHS0338/MDA-T7-BC05/ -o ./MDA-T7-BC05/ -S human -F fastq
Traceback (most recent call last):
  File "NanoReviser.py", line 26, in <module>
    from albacore.path_utils import get_default_path
ModuleNotFoundError: No module named 'albacore'

Thanks;

**Comment by Christoph-Ammer** [comment]
Hi 
I also faced the same problem. I installed albacore after downloading from official ONT webpage with following commant
`python -m pip install ont_albacore-2.3.4-cp36-cp36m-manylinux1_x86_64.whl 
Processing ./ont_albacore-2.3.4-cp36-cp36m-manylinux1_x86_64.whl`
Hope that helps!!
Best

**Comment by Christoph-Ammer** [comment]
sorry the command was only
`python -m pip install ont_albacore-2.3.4-cp36-cp36m-manylinux1_x86_64.whl`
afterwards I ran 
`python NanoReviser.py -d ./unitest/test_data/fast5/ -o ./unitest_nanorev_results/ -S ecoli -F fastq` 
and it worked.

**Comment by desmodus1984** [comment]
Well. It doesn't help much.
I have processed my reads with Guppy not with Albacore which is not supported nor recommended by ONT.

Get BlueMail for Android<http://www.bluemail.me/r?b=16117>
On Jan 12, 2021, at 05:36, Christoph-Ammer <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi
I also faced the same problem. I installed albacore after downloading from official ONT webpage with following commant
python -m pip install ont_albacore-2.3.4-cp36-cp36m-manylinux1_x86_64.whl Processing ./ont_albacore-2.3.4-cp36-cp36m-manylinux1_x86_64.whl
Hope that helps!!
Best

**Comment by Christoph-Ammer** [comment]
I agree! But the tool just works with albacore. Also in their paper the authors did not include analysis with guppy. I will try to compare the results from nanoreviser with these from guppy and if I do not see any significant differences I will stick to the official workflow from ONT --> guppy:-)
